pretrained: "./pretrained_models/adapter_base.ckpt"
data:
    modality: "pose"
    train_pipeline:
        dataset:
            _target_: openhands.datasets.isolated.WLASLDataset
            split_file: /misery/lee/asllex_large.json
            root_dir: /misery/lee/asllex_large/poses
            splits: "train"
            modality: "pose"

        transforms:
            - PoseSelect:
                preset: mediapipe_holistic_minimal_27
            - CenterAndScaleNormalize:
                reference_points_preset: shoulder_mediapipe_holistic_minimal_27
                scale_factor: 1
            - ShearTransform:
                shear_std: 0.1
            - RotatationTransform:
                rotation_std: 0.1

        dataloader:
            _target_: torch.utils.data.DataLoader
            batch_size: 32
            shuffle: true
            num_workers: 6
            pin_memory: true
            drop_last: true
    
        parameters: 
            [
                "Handshape",
                # "Selected Fingers",
                # "Flexion",
                # "Spread",
                # "Spread Change",
                # "Thumb Position",
                # "Thumb Contact",
                # "Sign Type",
                # "Path Movement",
                # "Repeated Movement",
                # "Major Location",
                # "Minor Location",
                # "Second Minor Location",
                # "Contact",
                # "Nondominant Handshape", 
                # "Wrist Twist",
                # "Handshape Morpheme 2"
            ]



    valid_pipeline:
        dataset:
            _target_: openhands.datasets.isolated.WLASLDataset
            split_file: /misery/lee/asllex_large.json
            root_dir: /misery/lee/asllex_large/poses
            splits: "test"
            modality: "pose"

        transforms:
            - PoseSelect:
                preset: mediapipe_holistic_minimal_27
            - CenterAndScaleNormalize:
                reference_points_preset: shoulder_mediapipe_holistic_minimal_27
                scale_factor: 1

        dataloader:
            _target_: torch.utils.data.DataLoader
            batch_size: 32
            shuffle: false
            num_workers: 3
            pin_memory: true
            drop_last: false

        parameters: 
            [
                # "Handshape",
                # "Selected Fingers",
                # "Flexion",
                # "Spread",
                # "Spread Change",
                # "Thumb Position",
                # "Thumb Contact",
                # "Sign Type",
                # "Path Movement",
                # "Repeated Movement",
                # "Major Location",
                "Minor Location",
                # "Second Minor Location",
                # "Contact",
                # "Nondominant Handshape", 
                # "Wrist Twist",
                # "Handshape Morpheme 2"
            ]


model:
    learn_adapter: True
    adapter_strategy: "vanilla"
    adapters_dir: "/home/lee/wlasl/slgcn_adapters/pretrained_models/vanilla_adapters/"
    #adapter_source: ["/home/lee/wlasl/slgcn_adapters/pretrained_models/vanilla_adapters/selectedfingers.adpt", "/home/lee/wlasl/slgcn_adapters/pretrained_models/vanilla_adapters/flexion.adpt"]
    encoder:
        type: decoupled-gcn
        params:
            graph_args:
                num_nodes: 27
                inward_edges:
                    [
                        [2, 0],
                        [1, 0],
                        [0, 3],
                        [0, 4],
                        [3, 5],
                        [4, 6],
                        [5, 7],
                        [6, 17],
                        [7, 8],
                        [7, 9],
                        [9, 10],
                        [7, 11],
                        [11, 12],
                        [7, 13],
                        [13, 14],
                        [7, 15],
                        [15, 16],
                        [17, 18],
                        [17, 19],
                        [19, 20],
                        [17, 21],
                        [21, 22],
                        [17, 23],
                        [23, 24],
                        [17, 25],
                        [25, 26],
                    ]
    decoder:
        type: param_fc
        params:
            dropout_ratio: 0

optim:
    loss: 'CrossEntropyLoss'
    optimizer:
        name: Adam
        params:
            lr: 1e-3

    scheduler:
        name: CosineAnnealingLR
        params:
            last_epoch: -1
            T_max: 10

trainer:
    gpus: 1
    max_epochs: 100
    resume_from_checkpoint: false #./pretrained_models/mjr_sample.ckpt

exp_manager:
    create_tensorboard_logger: true
    create_wandb_logger: false
    wandb_logger_kwargs:
        name: gcn_individual_fusion
        project: openhands
        entity: asl-adapters
        api_key: 

    create_checkpoint_callback: true
    checkpoint_callback_params:
        monitor: "val_acc"
        mode: "max"
        save_top_k: 1
        dirpath: "./pretrained_models/"

    early_stopping_callback: true
    early_stopping_params:
        monitor: "val_acc"
        patience: 80
        verbose: true
        mode: "max"
